Searchable support Elasticsearch 7 (Cleanup)
pagemachine/searchable pull request #136
Opened 2024-07-02 16:33 UTC by fseipel

Cleanup of #88

2024-07-03 08:50 UTC, mbrodala commented
Can you fix/update the failing functional test?

2024-07-03 08:51 UTC, fseipel commented
> Can you fix/update the failing functional test?

I am already on it

2024-07-03 10:26 UTC, mbrodala requested changes

2024-07-03 10:26 UTC, mbrodala commented on Classes/Service/ExtconfService.php
> +    public static function getEnviormentOfIndex($indexName)
```suggestion
    public static function getEnvironmentOfIndex($indexName)
```

2024-07-03 10:26 UTC, mbrodala commented on Classes/Service/ExtconfService.php
> +    public static function getIndecesByLanguage($language = 0)
```suggestion
    public static function getIndicesByLanguage($language = 0)
```

2024-07-03 10:26 UTC, mbrodala commented on Classes/Service/ExtconfService.php
> +     * Returns the index language for a given name, if set. Otherwise throws an error so no invalid indices are created
```suggestion
     * Returns the language indices for a given language, if set. Otherwise throws an error so no invalid indices are created
```

2024-07-03 10:26 UTC, mbrodala commented on Classes/Service/ExtconfService.php
> +    public static function getIndecesByLanguage($language = 0)
```suggestion
    public static function getIndecesByLanguage(int $language = 0)
```

We should prefer native types.

2024-07-03 10:26 UTC, mbrodala commented on Classes/Service/IndexingService.php
> +            $indeces = ExtconfService::getIndecesByLanguage($language);
```suggestion
            $indices = ExtconfService::getIndecesByLanguage($language);
```

... and possibly other places.

2024-07-03 10:26 UTC, mbrodala commented on doc/migration/6-0.md
> +- Update to the slightly changed `indices` definition
We should add a little more explanation here:

1. Explain what `'0'` and `'name'` did do before and if anything of this was arbitrary
2. Explain what `'english'` and `'typo3_language'` do now and if anything of this is arbitrary

2024-07-03 10:26 UTC, mbrodala commented on docker-compose.yml
> +      - ingest.geoip.downloader.enabled=false
What is this line for?

2024-07-09 08:47 UTC, fseipel commented on docker-compose.yml
> +      - ingest.geoip.downloader.enabled=false
Stops the download of geoip databases at startup. Nothing in the tests needs it.

2024-07-09 10:13 UTC, mbrodala commented on docker-compose.yml
> +      - ingest.geoip.downloader.enabled=false
OK, got it. A separate commit which explains exactly this would have clarified it.

2024-07-09 10:47 UTC, mbrodala commented
I am unable to execute the `index:setup` command:

```
$ typo3 index:setup

                                                                                                                                      
  [ TYPO3\CMS\Core\Error\Exception ]                                                                                                  
  PHP Warning: Undefined array key "name" in /var/www/html/vendor/pagemachine/searchable/Classes/Service/ExtconfService.php line 172  
                                                                                                                                      

index:setup
```

Apparently there is nothing in `$indeces` (another typo BTW) for `searchable_updates` so this fails. What should happen instead?

Notice that my indices don't have a `name` key anymore as [the migration suggests](https://github.com/pagemachine/searchable/blob/ES7V2/doc/migration/6-0.md) that it can be dropped.

2024-07-09 11:55 UTC, fseipel commented
> I am unable to execute the `index:setup` command:
> 
> ```
> $ typo3 index:setup
> 
>                                                                                                                                       
>   [ TYPO3\CMS\Core\Error\Exception ]                                                                                                  
>   PHP Warning: Undefined array key "name" in /var/www/html/vendor/pagemachine/searchable/Classes/Service/ExtconfService.php line 172  
>                                                                                                                                       
> 
> index:setup
> ```
> 
> Apparently there is nothing in `$indeces` (another typo BTW) for `searchable_updates` so this fails. What should happen instead?
> 
> Notice that my indices don't have a `name` key anymore as [the migration suggests](https://github.com/pagemachine/searchable/blob/ES7V2/doc/migration/6-0.md) that it can be dropped.

It was old name based matching which I missed. Not it should work.

2024-07-10 07:05 UTC, mbrodala requested changes

2024-07-10 07:05 UTC, mbrodala commented on Classes/Query/AbstractQuery.php
> +    public function getIndices()
```suggestion
    public function getIndices(): void
```

2024-07-10 07:05 UTC, mbrodala commented on Classes/Query/AbstractQuery.php
> +    public function setIndices($indices)
```suggestion
    public function setIndices(array $indices): void
```

2024-07-10 07:05 UTC, mbrodala commented on Classes/Query/AbstractQuery.php
> +    public function addIndex($index)
```suggestion
    public function addIndex(string $index): static
```

2024-07-10 07:05 UTC, mbrodala commented on Classes/Query/AbstractQuery.php
> +    public function removeIndex($index)
```suggestion
    public function removeIndex(string $index): static
```

2024-07-10 07:05 UTC, mbrodala commented on Classes/Query/AbstractQuery.php
> +    public function getElasticsearchIndices()
```suggestion
     */
    public function getElasticsearchIndices(): array
```

2024-07-10 07:05 UTC, mbrodala commented on Classes/Query/AbstractQuery.php
> +    protected function getActiveIndices()
```suggestion
     */
    protected function getActiveIndices(): array
```

2024-07-10 07:05 UTC, mbrodala commented on Classes/Service/ExtconfService.php
> +     * This is necessary because since elastic 7.0 one indice can only have one document type.
```suggestion
     * Creates a new ES indice for every index/indexer combination in the config. This keeps the configuration simple even if it is not the real index structure in elasticsearch.
     * This is necessary because since elastic 7.0 one index can only have one document type.
```

:es:

2024-07-30 14:26 UTC, mbrodala commented
From what I could test it works fairly well, so let's get this merged.

2024-07-30 14:27 UTC, mbrodala approved these changes

2024-07-30 14:27 UTC, merged