Searchable support Elasticsearch 7
pagemachine/searchable pull request #62
Opened 2022-02-21 15:23 UTC by NilsFGFriedrich

Moves Searchable to Elasticsearch 7.
Index configuration in ext_localconf.php needs to be updated, so you have one Index per Indexer and language.
Some Indexer configuration need updating, if they don't support current Elasticsearch 7 options, like Parent/Child (see: https://www.elastic.co/de/blog/removal-of-mapping-types-elasticsearch#parent-child)

2022-02-21 15:26 UTC, mbrodala commented
@NilsFGFriedrich Can you do a rebase?

2022-02-21 19:13 UTC, NilsFGFriedrich commented
@mbrodala the rebase should be here

2022-05-23 16:43 UTC, mbrodala commented
Sorry for the delay, can you do another rebase? Also check locally if the tests succeed for TYPO3v9 and TYPO3v10.

If it's too much hassle then we can drop support for TYPO3v9 separately; then you can rebase on top of that.

2022-05-24 13:35 UTC, mbrodala requested changes
I've stopped for now. First I'll drop support for TYPO3v9 in `master` and drop all deprecations.

2022-05-24 13:35 UTC, mbrodala commented on ext_localconf.php
> +        'number_of_shards' => 1,
Why was this reduced? There is no explanation in your commit.

2022-05-24 13:35 UTC, mbrodala commented on Classes/Command/Index/ResetCommand.php
> +        // $language = $input->getArgument('language');
This looks odd, please remove all interim/debug comments.

2022-05-24 13:35 UTC, mbrodala commented on Classes/Command/Index/ResetCommand.php
> +         $this->indexingService->resetIndex($nameIndex);
Please keep the indentation.

2022-05-24 13:35 UTC, mbrodala commented on Classes/Command/SearchableCommandController.php
>       * @deprecated since Searchable v3, will be removed with Searchable v4, use "index:reset" instead
Just noticed this deprecation but v4 was released yesterday. Guess we should drop this in `master` at least to have it ready for Searchable v5. I'll take care of this, then you can rebase and skip this.

2022-05-24 13:35 UTC, mbrodala commented on Classes/Configuration/ConfigurationManager.php
> +             if (in_array(MapperInterface::class, class_implements($indexerConfiguration['config']['mapper']['className']))) {
See above, better fix the indentation everywhere.

2022-05-24 13:35 UTC, mbrodala commented on Classes/Feature/HighlightFeature.php
> -            'include_in_all' => false,
Why was this removed? Please check all commits and add an explanation for every non-obvious change. Otherwise it's hard to understand why things where changed.

2022-05-24 15:19 UTC, mbrodala commented
FYI²: I've prepared the CI for testing with multiple ES versions: https://github.com/pagemachine/searchable/pull/78

2022-06-28 15:08 UTC, NilsFGFriedrich commented
The CI / build (7.4, ^10.4, 7.17.4) did complete this time: https://github.com/NilsFGFriedrich/searchable/runs/7095369196?check_suite_focus=true 
Not sure why it only does this occasionally.

2022-11-22 12:12 UTC, merged